# Generated by Django 3.2.3 on 2021-05-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000)),
                ('response', models.CharField(blank=True, max_length=500)),
                ('permit', models.CharField(blank=True, max_length=500)),
                ('comments', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
